---
language: node_js
sudo: false
node_js:
  - "lts/*"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

install:
  - npm install

script:
  - npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
  - npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
  - npm run doc
  - npx ng lint
  - npx ng build --prod

deploy:
  - provider: script
    skip_cleanup: true
    script: scripts/travis-deploy.sh
    on:
      branch: master
